"""add sales columns to transactions

Revision ID: 26192a15f2c2
Revises: 03d4f664e2ea
Create Date: 2026-09-14 22:56:05.439594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26192a15f2c2'
down_revision: Union[str, Sequence[str], None] = '03d4f664e2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('content', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('settlement_status', sa.String(length=20), server_default='none', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'settlement_status')
    op.drop_column('transactions', 'content')
    op.drop_column('transactions', 'payment_method')
    # ### end Alembic commands ###
