"""add external support programs table

Revision ID: 7014d2ace8a2
Revises: 2e51546c423a
Create Date: 2026-09-17 09:39:49.714336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7014d2ace8a2'
down_revision: Union[str, Sequence[str], None] = '2e51546c423a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_support_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('agency', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('apply_start_date', sa.Date(), nullable=True),
    sa.Column('apply_end_date', sa.Date(), nullable=True),
    sa.Column('detail_url', sa.String(length=500), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_support_programs_external_id'), 'external_support_programs', ['external_id'], unique=True)
    op.create_index(op.f('ix_external_support_programs_source'), 'external_support_programs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_support_programs_source'), table_name='external_support_programs')
    op.drop_index(op.f('ix_external_support_programs_external_id'), table_name='external_support_programs')
    op.drop_table('external_support_programs')
    # ### end Alembic commands ###
