"""add fee_amount to transactions

Revision ID: cb2c144f440f
Revises: 26192a15f2c2
Create Date: 2026-09-14 23:00:51.125386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2c144f440f'
down_revision: Union[str, Sequence[str], None] = '26192a15f2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fee_amount', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'fee_amount')
    # ### end Alembic commands ###
