"""update store information

Revision ID: e9348d81ed75
Revises: 20066607f037
Create Date: 2026-09-09 04:12:48.991107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9348d81ed75'
down_revision: Union[str, Sequence[str], None] = '20066607f037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('industry_name', sa.String(length=100), nullable=False))
    op.drop_column('stores', 'industry_code')
    op.drop_column('stores', 'region_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('region_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('industry_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('stores', 'industry_name')
    # ### end Alembic commands ###
