"""add diagnosis_reports, transactions, industry_benchmarks, financial_products

Revision ID: f1f73e95a91d
Revises: e9348d81ed75
Create Date: 2026-09-08 16:25:23.990622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1f73e95a91d'
down_revision: Union[str, Sequence[str], None] = 'e9348d81ed75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('limit_amount', sa.BigInteger(), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('eligibility_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('avg_monthly_sales', sa.BigInteger(), nullable=False),
    sa.Column('avg_labor_cost_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_rent_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_other_cost_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_benchmarks_industry'), 'industry_benchmarks', ['industry'], unique=False)
    op.create_index(op.f('ix_industry_benchmarks_region'), 'industry_benchmarks', ['region'], unique=False)
    op.create_table('diagnosis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=False),
    sa.Column('composite_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('sub_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_reports_user_id'), 'diagnosis_reports', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_diagnosis_reports_user_id'), table_name='diagnosis_reports')
    op.drop_table('diagnosis_reports')
    op.drop_index(op.f('ix_industry_benchmarks_region'), table_name='industry_benchmarks')
    op.drop_index(op.f('ix_industry_benchmarks_industry'), table_name='industry_benchmarks')
    op.drop_table('industry_benchmarks')
    op.drop_table('financial_products')
    # ### end Alembic commands ###
